/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolePoleIdRouteImport } from './routes/pole/$poleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolePoleIdRoute = PolePoleIdRouteImport.update({
  id: '/pole/$poleId',
  path: '/pole/$poleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pole/$poleId': typeof PolePoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pole/$poleId': typeof PolePoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pole/$poleId': typeof PolePoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pole/$poleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pole/$poleId'
  id: '__root__' | '/' | '/pole/$poleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolePoleIdRoute: typeof PolePoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pole/$poleId': {
      id: '/pole/$poleId'
      path: '/pole/$poleId'
      fullPath: '/pole/$poleId'
      preLoaderRoute: typeof PolePoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolePoleIdRoute: PolePoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
